<?php
  /**
   * Implementation of hook_form_alter().
   *
   * The function is named modulename_form_alter.
   */
  function custom_vbo_taxonomy_form_alter(&$form, $form_state, $form_id) {
    // Normally a switch is used because you may want to alter more than
    // one form and it is easy to add a new case for each form.
    switch ($form_id) {
      // This is our form ID.
      case 'views_bulk_operations_form__1':
        // Our kickin' mods go here.
        // dsm($form);
       unset($form['do']['#options'][1]);
       $taxonomykeys = array_keys($form['taxonomy']);
       foreach($taxonomykeys as $taxonomykey) {
         if($taxonomykey<>9 && $taxonomykey<>6 && substr_compare($taxonomykey, "#", 0, 1)) { 
           unset($form['taxonomy'][$taxonomykey]);
           }
       }
         // if the user is does not have administer nodes permission, do not allow
         // them to change/add audiences beyond the current group
       case 'article_node_form':
          if(!user_access('administer nodes')) {
           foreach($form['og_nodeapi']['visible']['og_groups']['#options'] as $key => $group) {
             if (!isset($form['og_initial_groups']['#value'][$key])) {
                 unset($form['og_nodeapi']['visible']['og_groups']['#options'][$key]);
             }
            }
         }
         
      break;
    }
  }
  
?>